# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cover',
            field=models.URLField(default=None, null=True),
        ),
    ]
