# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_item_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='most_vote_num',
            field=models.IntegerField(default=0),
        ),
    ]
